from __future__ import annotations

from tracecase_model import (
    BoundaryKind,
    ComponentKind,
    DerivationKind,
    EffectKind,
    NodeKind,
    PropagationContract,
    RelationKind,
    SensitivityLabel,
)

from .models import (
    BooleanParameterDomain,
    ContextContractSpec,
    EffectContractSpec,
    EnumParameterDomain,
    FaultOperatorClass,
    FaultOperatorDefinition,
    FaultOperatorKind,
    FaultTargetKind,
    IntegerRangeParameterDomain,
    MinimizationStrategy,
    ObservabilityProfile,
    ResourceTemplate,
    ScenarioFamily,
    ScenarioFamilyClass,
    ScenarioRegistry,
    TopologyEdge,
    TopologyMotifKind,
    TopologyRole,
    TopologyTemplate,
    UniverseAxis,
)


def build_default_registry() -> ScenarioRegistry:
    invariants = {
        "invariant.context.required-continuity.v1": "Required context remains equivalent across its declared path.",
        "invariant.context.forbidden-propagation.v1": "Forbidden context does not cross the selected boundary.",
        "invariant.identity.execution-isolation.v1": "Independent executions remain distinguishable.",
        "invariant.identity.workflow-correlatable.v1": "One logical workflow remains correlatable across boundaries.",
        "invariant.effect.at-most-once.v1": "A logical effect becomes durable no more than its allowed count.",
        "invariant.effect.required-eventuality.v1": "A required effect eventually occurs.",
        "invariant.ordering.read-after-visibility.v1": "Dependent reads occur only after producer state becomes visible.",
        "invariant.consistency.required-freshness.v1": "Observed state meets its declared freshness contract.",
        "invariant.contract.schema-compatible.v1": "Producer and consumer schema ranges overlap.",
        "invariant.resource.capacity-bounded.v1": "Required resource capacity remains within declared limits.",
        "invariant.performance.work-amplification.v1": "Logical work remains within its expected amplification bound.",
        "invariant.observability.required-linkage.v1": "Required execution linkage exists across boundaries.",
        "invariant.privacy.prohibited-capture.v1": "Prohibited sensitive values are not captured or exported.",
    }

    async_effect = TopologyTemplate(
        topology_id="topology.async-effect.v1",
        motif=TopologyMotifKind.ASYNC_HANDOFF,
        roles=(
            TopologyRole(
                role_id="role.request",
                component_kind=ComponentKind.API,
                node_kind=NodeKind.REQUEST_HANDLER,
                operation="workflow.accept",
                stage=0,
                component_role="producer",
            ),
            TopologyRole(
                role_id="role.publish",
                component_kind=ComponentKind.API,
                node_kind=NodeKind.MESSAGE_PUBLISH,
                operation="workflow.publish",
                stage=1,
                component_role="producer",
            ),
            TopologyRole(
                role_id="role.consume",
                component_kind=ComponentKind.WORKER,
                node_kind=NodeKind.TASK_ATTEMPT,
                operation="workflow.consume",
                stage=2,
                component_role="consumer",
            ),
            TopologyRole(
                role_id="role.write",
                component_kind=ComponentKind.DATABASE,
                node_kind=NodeKind.WRITE,
                operation="workflow.persist",
                stage=3,
                component_role="state-store",
                default_status="committed",
            ),
        ),
        edges=(
            TopologyEdge(
                edge_id="edge.request-publish",
                source_role_ref="role.request",
                target_role_ref="role.publish",
                relation_kind=RelationKind.PUBLISHES,
                boundary_kind=BoundaryKind.MESSAGE_PUBLISH,
                boundary_name="asynchronous publish",
            ),
            TopologyEdge(
                edge_id="edge.publish-consume",
                source_role_ref="role.publish",
                target_role_ref="role.consume",
                relation_kind=RelationKind.DELIVERS,
                boundary_kind=BoundaryKind.MESSAGE_CONSUME,
                boundary_name="message delivery",
                derivation=DerivationKind.SOURCE_NATIVE,
            ),
            TopologyEdge(
                edge_id="edge.consume-write",
                source_role_ref="role.consume",
                target_role_ref="role.write",
                relation_kind=RelationKind.WRITES_TO,
                boundary_kind=BoundaryKind.DATABASE,
                boundary_name="durable write",
            ),
        ),
        resources=(
            ResourceTemplate(
                resource_id="resource.workflow-state",
                kind="logical_aggregate",
                name="Workflow state",
                owner_role_ref="role.write",
                sensitivity={SensitivityLabel.TENANT_IDENTIFIER},
            ),
        ),
        contexts=(
            ContextContractSpec(
                contract_id="contract.tenant-context",
                namespace="tenant",
                field_name="tenant_id",
                value="tenant-alpha",
                propagation_contract=PropagationContract.REQUIRED,
                source_role_ref="role.request",
                required_role_refs=("role.consume",),
                sensitivity={SensitivityLabel.TENANT_IDENTIFIER},
            ),
            ContextContractSpec(
                contract_id="contract.workflow-context",
                namespace="workflow",
                field_name="run_id",
                value="workflow-synthetic-001",
                propagation_contract=PropagationContract.REQUIRED,
                source_role_ref="role.request",
                required_role_refs=("role.publish", "role.consume"),
                sensitivity={SensitivityLabel.INTERNAL},
            ),
        ),
        effects=(
            EffectContractSpec(
                contract_id="contract.workflow-effect",
                effect_kind=EffectKind.STATE_UPDATE,
                logical_effect_key="workflow/synthetic-001/completed",
                producer_role_ref="role.consume",
                target_resource_ref="resource.workflow-state",
                operation="mark workflow complete",
                maximum_durable_count=1,
                idempotency_key="workflow-synthetic-001-complete",
            ),
        ),
    )

    transactional_async = TopologyTemplate(
        topology_id="topology.transactional-async.v1",
        motif=TopologyMotifKind.TRANSACTIONAL_ASYNC,
        roles=(
            TopologyRole(
                role_id="role.tx-request",
                component_kind=ComponentKind.API,
                node_kind=NodeKind.REQUEST_HANDLER,
                operation="state.create-request",
                stage=0,
                component_role="producer",
            ),
            TopologyRole(
                role_id="role.transaction",
                component_kind=ComponentKind.DATABASE,
                node_kind=NodeKind.TRANSACTION,
                operation="state.transaction",
                stage=1,
                component_role="state-store",
                default_status="committed",
            ),
            TopologyRole(
                role_id="role.tx-publish",
                component_kind=ComponentKind.API,
                node_kind=NodeKind.MESSAGE_PUBLISH,
                operation="state.publish",
                stage=2,
                component_role="producer",
            ),
            TopologyRole(
                role_id="role.tx-consume",
                component_kind=ComponentKind.WORKER,
                node_kind=NodeKind.TASK_ATTEMPT,
                operation="state.consume",
                stage=3,
                component_role="consumer",
            ),
            TopologyRole(
                role_id="role.read",
                component_kind=ComponentKind.DATABASE,
                node_kind=NodeKind.READ,
                operation="state.read",
                stage=4,
                component_role="state-store",
            ),
        ),
        edges=(
            TopologyEdge(
                edge_id="edge.request-transaction",
                source_role_ref="role.tx-request",
                target_role_ref="role.transaction",
                relation_kind=RelationKind.CONTAINS,
                boundary_kind=BoundaryKind.TRANSACTION,
            ),
            TopologyEdge(
                edge_id="edge.request-tx-publish",
                source_role_ref="role.tx-request",
                target_role_ref="role.tx-publish",
                relation_kind=RelationKind.PUBLISHES,
                boundary_kind=BoundaryKind.MESSAGE_PUBLISH,
            ),
            TopologyEdge(
                edge_id="edge.tx-publish-consume",
                source_role_ref="role.tx-publish",
                target_role_ref="role.tx-consume",
                relation_kind=RelationKind.DELIVERS,
                boundary_kind=BoundaryKind.MESSAGE_CONSUME,
            ),
            TopologyEdge(
                edge_id="edge.consume-read",
                source_role_ref="role.tx-consume",
                target_role_ref="role.read",
                relation_kind=RelationKind.READS_FROM,
                boundary_kind=BoundaryKind.DATABASE,
            ),
        ),
        resources=(
            ResourceTemplate(
                resource_id="resource.transactional-state",
                kind="database_row",
                name="Transactional state",
                owner_role_ref="role.transaction",
            ),
        ),
        contexts=(
            ContextContractSpec(
                contract_id="contract.transaction-workflow",
                namespace="workflow",
                field_name="run_id",
                value="workflow-transaction-001",
                propagation_contract=PropagationContract.REQUIRED,
                source_role_ref="role.tx-request",
                required_role_refs=("role.tx-consume",),
            ),
        ),
    )

    sync_chain = TopologyTemplate(
        topology_id="topology.sync-chain.v1",
        motif=TopologyMotifKind.SYNCHRONOUS_CHAIN,
        roles=(
            TopologyRole(
                role_id="role.client",
                component_kind=ComponentKind.CLIENT,
                node_kind=NodeKind.CLIENT_REQUEST,
                operation="client.invoke",
                stage=0,
            ),
            TopologyRole(
                role_id="role.service",
                component_kind=ComponentKind.SERVICE,
                node_kind=NodeKind.SERVICE_OPERATION,
                operation="service.handle",
                stage=1,
            ),
            TopologyRole(
                role_id="role.dependency",
                component_kind=ComponentKind.EXTERNAL_SERVICE,
                node_kind=NodeKind.EXTERNAL_REQUEST,
                operation="dependency.call",
                stage=2,
            ),
        ),
        edges=(
            TopologyEdge(
                edge_id="edge.client-service",
                source_role_ref="role.client",
                target_role_ref="role.service",
                relation_kind=RelationKind.INVOKES,
                boundary_kind=BoundaryKind.HTTP,
            ),
            TopologyEdge(
                edge_id="edge.service-dependency",
                source_role_ref="role.service",
                target_role_ref="role.dependency",
                relation_kind=RelationKind.INVOKES,
                boundary_kind=BoundaryKind.EXTERNAL_DEPENDENCY,
            ),
        ),
        contexts=(
            ContextContractSpec(
                contract_id="contract.request-context",
                namespace="request",
                field_name="request_id",
                value="request-synthetic-001",
                propagation_contract=PropagationContract.REQUIRED,
                source_role_ref="role.client",
                required_role_refs=("role.service",),
            ),
        ),
    )

    fan_out = TopologyTemplate(
        topology_id="topology.fan-out.v1",
        motif=TopologyMotifKind.FAN_OUT,
        roles=(
            TopologyRole(
                role_id="role.fan-root",
                component_kind=ComponentKind.SERVICE,
                node_kind=NodeKind.SERVICE_OPERATION,
                operation="fanout.root",
                stage=0,
            ),
            TopologyRole(
                role_id="role.fan-child",
                component_kind=ComponentKind.WORKER,
                node_kind=NodeKind.TASK_ATTEMPT,
                operation="fanout.child",
                stage=1,
            ),
        ),
        edges=(
            TopologyEdge(
                edge_id="edge.fan-root-child",
                source_role_ref="role.fan-root",
                target_role_ref="role.fan-child",
                relation_kind=RelationKind.SPAWNS,
                boundary_kind=BoundaryKind.MESSAGE_PUBLISH,
            ),
        ),
    )

    fault_operators = (
        _fault(
            "fault.drop-context.v1",
            FaultOperatorKind.DROP_CONTEXT_FIELD,
            FaultOperatorClass.SEMANTIC,
            "Drop required context",
            (FaultTargetKind.CONTEXT, FaultTargetKind.ROLE),
            (UniverseAxis.BOUNDARY_PROPAGATION,),
        ),
        _fault(
            "fault.mutate-context.v1",
            FaultOperatorKind.MUTATE_CONTEXT_FIELD,
            FaultOperatorClass.SEMANTIC,
            "Mutate propagated context",
            (FaultTargetKind.CONTEXT, FaultTargetKind.ROLE),
            (UniverseAxis.BOUNDARY_PROPAGATION,),
            parameter_domains=(
                EnumParameterDomain(parameter="replacement", values=("tenant-beta", "default", ""), default="tenant-beta"),
            ),
        ),
        _fault(
            "fault.copy-other-scope-context.v1",
            FaultOperatorKind.COPY_CONTEXT_FROM_OTHER_SCOPE,
            FaultOperatorClass.SEMANTIC,
            "Copy context from another isolation scope",
            (FaultTargetKind.CONTEXT, FaultTargetKind.ROLE),
            (UniverseAxis.ISOLATION_PRIVACY, UniverseAxis.TIME_CONCURRENCY),
        ),
        _fault(
            "fault.break-trace-link.v1",
            FaultOperatorKind.BREAK_TRACE_LINK,
            FaultOperatorClass.OBSERVABILITY,
            "Break causal trace linkage",
            (FaultTargetKind.EDGE, FaultTargetKind.ROLE),
            (UniverseAxis.OBSERVABILITY_EVIDENCE,),
        ),
        _fault(
            "fault.collapse-execution-identity.v1",
            FaultOperatorKind.COLLAPSE_EXECUTION_IDENTITY,
            FaultOperatorClass.SEMANTIC,
            "Collapse independent executions onto one identity",
            (FaultTargetKind.SYSTEM, FaultTargetKind.ROLE),
            (UniverseAxis.ISOLATION_PRIVACY, UniverseAxis.OBSERVABILITY_EVIDENCE),
        ),
        _fault(
            "fault.duplicate-effect.v1",
            FaultOperatorKind.DUPLICATE_EFFECT,
            FaultOperatorClass.SEMANTIC,
            "Repeat a logical durable effect",
            (FaultTargetKind.EFFECT, FaultTargetKind.ROLE),
            (UniverseAxis.STATE_EFFECTS, UniverseAxis.FAILURE_RECOVERY),
            parameter_domains=(IntegerRangeParameterDomain(parameter="copies", minimum=2, maximum=4, default=2),),
        ),
        _fault(
            "fault.omit-effect.v1",
            FaultOperatorKind.OMIT_EFFECT,
            FaultOperatorClass.SEMANTIC,
            "Omit a required effect",
            (FaultTargetKind.EFFECT,),
            (UniverseAxis.STATE_EFFECTS,),
        ),
        _fault(
            "fault.fail-after-effect.v1",
            FaultOperatorKind.FAIL_AFTER_EFFECT,
            FaultOperatorClass.SEMANTIC,
            "Fail after the effect but before acknowledgement",
            (FaultTargetKind.EFFECT, FaultTargetKind.ROLE),
            (UniverseAxis.FAILURE_RECOVERY, UniverseAxis.STATE_EFFECTS),
        ),
        _fault(
            "fault.delay-operation.v1",
            FaultOperatorKind.DELAY_OPERATION,
            FaultOperatorClass.SEMANTIC,
            "Delay an operation",
            (FaultTargetKind.ROLE,),
            (UniverseAxis.TIME_CONCURRENCY, UniverseAxis.RESOURCES_PERFORMANCE),
            parameter_domains=(IntegerRangeParameterDomain(parameter="delay_ms", minimum=10, maximum=1000, step=10, default=100),),
        ),
        _fault(
            "fault.reorder-operations.v1",
            FaultOperatorKind.REORDER_OPERATIONS,
            FaultOperatorClass.SEMANTIC,
            "Reorder operations across a required temporal boundary",
            (FaultTargetKind.EDGE, FaultTargetKind.ROLE),
            (UniverseAxis.TIME_CONCURRENCY,),
        ),
        _fault(
            "fault.drop-observation.v1",
            FaultOperatorKind.DROP_OBSERVATION,
            FaultOperatorClass.OBSERVABILITY,
            "Drop source evidence",
            (FaultTargetKind.OBSERVATION, FaultTargetKind.ROLE),
            (UniverseAxis.OBSERVABILITY_EVIDENCE,),
        ),
        _fault(
            "fault.clock-skew.v1",
            FaultOperatorKind.CLOCK_SKEW,
            FaultOperatorClass.OBSERVABILITY,
            "Skew one source clock",
            (FaultTargetKind.ROLE,),
            (UniverseAxis.TIME_CONCURRENCY, UniverseAxis.OBSERVABILITY_EVIDENCE),
            parameter_domains=(IntegerRangeParameterDomain(parameter="skew_ms", minimum=-1000, maximum=1000, step=100, default=500),),
        ),
        _fault(
            "fault.contradictory-observation.v1",
            FaultOperatorKind.INJECT_CONTRADICTORY_OBSERVATION,
            FaultOperatorClass.OBSERVABILITY,
            "Inject evidence that contradicts another source",
            (FaultTargetKind.OBSERVATION, FaultTargetKind.EFFECT),
            (UniverseAxis.OBSERVABILITY_EVIDENCE,),
        ),
        _fault(
            "fault.schema-version-skew.v1",
            FaultOperatorKind.SCHEMA_VERSION_SKEW,
            FaultOperatorClass.SEMANTIC,
            "Introduce producer and consumer schema skew",
            (FaultTargetKind.EDGE, FaultTargetKind.ROLE),
            (UniverseAxis.CONTRACT_EVOLUTION, UniverseAxis.DEPLOYMENT_CONFIGURATION),
        ),
        _fault(
            "fault.capture-prohibited-field.v1",
            FaultOperatorKind.CAPTURE_PROHIBITED_FIELD,
            FaultOperatorClass.OBSERVABILITY,
            "Capture a prohibited sensitive value",
            (FaultTargetKind.OBSERVATION, FaultTargetKind.SYSTEM),
            (UniverseAxis.ISOLATION_PRIVACY, UniverseAxis.OBSERVABILITY_EVIDENCE),
        ),
        _fault(
            "fault.exhaust-resource.v1",
            FaultOperatorKind.EXHAUST_RESOURCE,
            FaultOperatorClass.SEMANTIC,
            "Exhaust a bounded resource",
            (FaultTargetKind.RESOURCE, FaultTargetKind.ROLE),
            (UniverseAxis.RESOURCES_PERFORMANCE,),
        ),
        _fault(
            "fault.amplify-operation.v1",
            FaultOperatorKind.AMPLIFY_OPERATION,
            FaultOperatorClass.SEMANTIC,
            "Amplify logical work",
            (FaultTargetKind.ROLE,),
            (UniverseAxis.RESOURCES_PERFORMANCE,),
            parameter_domains=(IntegerRangeParameterDomain(parameter="factor", minimum=2, maximum=20, default=5),),
        ),
    )

    families = (
        _family(
            "family.continuity.context-disappearance.v1",
            "Required context disappears",
            ScenarioFamilyClass.CONTINUITY,
            "topology.async-effect.v1",
            (UniverseAxis.BOUNDARY_PROPAGATION, UniverseAxis.OBSERVABILITY_EVIDENCE),
            ("fault.drop-context.v1",),
            ("invariant.context.required-continuity.v1",),
            parameters=_common_async_parameters(),
        ),
        _family(
            "family.continuity.context-mutation.v1",
            "Required context mutates",
            ScenarioFamilyClass.CONTINUITY,
            "topology.async-effect.v1",
            (UniverseAxis.BOUNDARY_PROPAGATION,),
            ("fault.mutate-context.v1",),
            ("invariant.context.required-continuity.v1",),
            parameters=_common_async_parameters(),
        ),
        _family(
            "family.isolation.context-contamination.v1",
            "Context crosses isolation scopes",
            ScenarioFamilyClass.ISOLATION,
            "topology.async-effect.v1",
            (UniverseAxis.ISOLATION_PRIVACY, UniverseAxis.TIME_CONCURRENCY),
            ("fault.copy-other-scope-context.v1",),
            ("invariant.identity.execution-isolation.v1",),
            parameters=(BooleanParameterDomain(parameter="concurrent", default=True),),
        ),
        _family(
            "family.identity.execution-fragmentation.v1",
            "One workflow fragments into disconnected identities",
            ScenarioFamilyClass.IDENTITY,
            "topology.async-effect.v1",
            (UniverseAxis.OBSERVABILITY_EVIDENCE, UniverseAxis.BOUNDARY_PROPAGATION),
            ("fault.break-trace-link.v1",),
            ("invariant.identity.workflow-correlatable.v1", "invariant.observability.required-linkage.v1"),
        ),
        _family(
            "family.identity.execution-collapse.v1",
            "Independent executions collapse onto one identity",
            ScenarioFamilyClass.IDENTITY,
            "topology.async-effect.v1",
            (UniverseAxis.ISOLATION_PRIVACY, UniverseAxis.OBSERVABILITY_EVIDENCE),
            ("fault.collapse-execution-identity.v1",),
            ("invariant.identity.execution-isolation.v1",),
        ),
        _family(
            "family.effect.duplicate.v1",
            "Logical effect becomes durable more than once",
            ScenarioFamilyClass.EFFECT,
            "topology.async-effect.v1",
            (UniverseAxis.STATE_EFFECTS, UniverseAxis.FAILURE_RECOVERY),
            ("fault.duplicate-effect.v1", "fault.fail-after-effect.v1"),
            ("invariant.effect.at-most-once.v1",),
            parameters=(IntegerRangeParameterDomain(parameter="attempts", minimum=2, maximum=4, default=2),),
        ),
        _family(
            "family.effect.omission.v1",
            "Required effect never occurs",
            ScenarioFamilyClass.EFFECT,
            "topology.async-effect.v1",
            (UniverseAxis.STATE_EFFECTS, UniverseAxis.FAILURE_RECOVERY),
            ("fault.omit-effect.v1",),
            ("invariant.effect.required-eventuality.v1",),
        ),
        _family(
            "family.ordering.read-before-visibility.v1",
            "Consumer reads before producer state is visible",
            ScenarioFamilyClass.ORDERING,
            "topology.transactional-async.v1",
            (UniverseAxis.TIME_CONCURRENCY, UniverseAxis.STATE_EFFECTS),
            ("fault.reorder-operations.v1", "fault.delay-operation.v1"),
            ("invariant.ordering.read-after-visibility.v1",),
        ),
        _family(
            "family.consistency.stale-observation.v1",
            "Consumer observes stale state",
            ScenarioFamilyClass.CONSISTENCY,
            "topology.transactional-async.v1",
            (UniverseAxis.STATE_EFFECTS, UniverseAxis.TIME_CONCURRENCY),
            ("fault.delay-operation.v1",),
            ("invariant.consistency.required-freshness.v1",),
        ),
        _family(
            "family.contract.schema-incompatibility.v1",
            "Producer and consumer schemas are incompatible",
            ScenarioFamilyClass.CONTRACT,
            "topology.async-effect.v1",
            (UniverseAxis.CONTRACT_EVOLUTION, UniverseAxis.DEPLOYMENT_CONFIGURATION),
            ("fault.schema-version-skew.v1",),
            ("invariant.contract.schema-compatible.v1",),
            parameters=(
                EnumParameterDomain(parameter="producer_version", values=("1.0", "2.0"), default="2.0"),
                EnumParameterDomain(parameter="consumer_version", values=("1.0", "2.0"), default="1.0"),
            ),
        ),
        _family(
            "family.resource.capacity-exhaustion.v1",
            "Required resource capacity is exhausted",
            ScenarioFamilyClass.RESOURCE,
            "topology.sync-chain.v1",
            (UniverseAxis.RESOURCES_PERFORMANCE,),
            ("fault.exhaust-resource.v1",),
            ("invariant.resource.capacity-bounded.v1",),
            parameters=(IntegerRangeParameterDomain(parameter="capacity", minimum=1, maximum=10, default=2),),
        ),
        _family(
            "family.performance.execution-amplification.v1",
            "Logical work amplifies beyond its bound",
            ScenarioFamilyClass.PERFORMANCE,
            "topology.fan-out.v1",
            (UniverseAxis.RESOURCES_PERFORMANCE, UniverseAxis.EXECUTION_TOPOLOGY),
            ("fault.amplify-operation.v1",),
            ("invariant.performance.work-amplification.v1",),
            parameters=(IntegerRangeParameterDomain(parameter="expected_fanout", minimum=1, maximum=5, default=2),),
        ),
        _family(
            "family.observability.causal-gap.v1",
            "Required causal linkage is missing",
            ScenarioFamilyClass.OBSERVABILITY,
            "topology.async-effect.v1",
            (UniverseAxis.OBSERVABILITY_EVIDENCE,),
            ("fault.break-trace-link.v1", "fault.drop-observation.v1", "fault.clock-skew.v1"),
            ("invariant.observability.required-linkage.v1",),
            observability=(
                ObservabilityProfile.COMPLETE,
                ObservabilityProfile.MISSING_BOUNDARY,
                ObservabilityProfile.BROKEN_TRACE,
                ObservabilityProfile.CLOCK_SKEWED,
            ),
        ),
        _family(
            "family.privacy.prohibited-capture.v1",
            "Instrumentation captures prohibited sensitive data",
            ScenarioFamilyClass.PRIVACY,
            "topology.sync-chain.v1",
            (UniverseAxis.ISOLATION_PRIVACY, UniverseAxis.OBSERVABILITY_EVIDENCE),
            ("fault.capture-prohibited-field.v1",),
            ("invariant.privacy.prohibited-capture.v1",),
            observability=(ObservabilityProfile.COMPLETE, ObservabilityProfile.REDACTED),
        ),
    )

    return ScenarioRegistry(
        topologies=(async_effect, transactional_async, sync_chain, fan_out),
        fault_operators=fault_operators,
        families=families,
        invariant_catalog=invariants,
        attributes={
            "coverage_model": "orthogonal semantic universes",
            "family_count": len(families),
        },
    )


def _fault(
    operator_id: str,
    kind: FaultOperatorKind,
    operator_class: FaultOperatorClass,
    title: str,
    targets: tuple[FaultTargetKind, ...],
    axes: tuple[UniverseAxis, ...],
    *,
    parameter_domains=(),
) -> FaultOperatorDefinition:
    return FaultOperatorDefinition(
        operator_id=operator_id,
        kind=kind,
        operator_class=operator_class,
        title=title,
        description=title,
        target_kinds=targets,
        parameter_domains=parameter_domains,
        universe_axes=axes,
    )


def _family(
    family_id: str,
    title: str,
    family_class: ScenarioFamilyClass,
    topology_ref: str,
    axes: tuple[UniverseAxis, ...],
    faults: tuple[str, ...],
    invariants: tuple[str, ...],
    *,
    parameters=(),
    observability=(ObservabilityProfile.COMPLETE,),
) -> ScenarioFamily:
    return ScenarioFamily(
        family_id=family_id,
        title=title,
        description=title,
        family_class=family_class,
        universe_axes=axes,
        topology_ref=topology_ref,
        parameter_domains=parameters,
        allowed_fault_operator_refs=faults,
        invariant_refs=invariants,
        observability_profiles=observability,
        minimization=MinimizationStrategy(),
    )


def _common_async_parameters():
    return (
        EnumParameterDomain(
            parameter="boundary_variant",
            values=("message", "task", "http-callback"),
            default="message",
        ),
        EnumParameterDomain(
            parameter="context_field",
            values=("tenant.tenant_id", "workflow.run_id"),
            default="tenant.tenant_id",
        ),
    )
